# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /data/db
#  engine:
  wiredTiger:
    engineConfig:
      cacheSizeGB: 2

# where to write logging data.
systemLog:
  verbosity: 1

# network interfaces
net:
  port: 27027
  bindIp: 0.0.0.0


# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo

security:
  authorization: enabled
  keyFile: /keyfile


#operationProfiling:

replication:
  replSetName: demo

#sharding:

## Enterprise-Only Options:

#auditLog:

setParameter:
  mongotHost: mongodb-search:27028
  searchIndexManagementHostAndPort: mongodb-search:27028
  useGrpcForSearch: true
  searchTLSMode: disabled