syncSource:
   replicaSet:
      hostAndPort: "mongodb-enterprise:27027"
      scramAuth:
        username: root
        passwordFile: /tmp/mongodb-enterprise-root-password
storage:
   dataPath: /data/mongot
